# Generated by Django 5.1.3 on 2024-11-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_passphrase_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passphrase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_passphrase_ref', to='users.passphrase'),
        ),
        migrations.AlterField(
            model_name='passphrase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_passphrase', to='users.user'),
        ),
    ]
